name: Test

on:
  workflow_call: # Allow this workflow to be called by other workflows
    inputs: {}
    # secrets:
    #   CODECOV_TOKEN:
    #     required: true
  push:
    branches-ignore:
      - "dev"
      - "main"
    tags-ignore:
      - "v*.*.*"

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq curl kcov

      - name: Run tests
        run: |
          mkdir -p test-results
          bats --report-formatter junit \
              --output test-results \
              test/

      # - name: Generate coverage with kcov
      #   run: |
      #     mkdir -p coverage
      #     kcov \
      #       --include-path="$(pwd)" \
      #       --exclude-pattern=/usr,/test \
      #       coverage \
      #       bats test/

      - name: Upload JUnit report
        if: always()
        # https://github.com/actions/upload-artifact/releases/tag/v7.0.1
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: report.xml
          path: test-results/

      # - name: Upload HTML coverage
      #   if: always()
      #   uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      #   with:
      #     name: kcov-html
      #     path: coverage/

      # - name: Upload coverage to Codecov
      #   # https://github.com/codecov/codecov-action/releases/tag/v6.0.1
      #   uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354
      #   with:
      #     files: coverage/cobertura.xml
      #     token: ${{ secrets.CODECOV_TOKEN }}

